name: upnp
version: 1.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: Universal Plugin and Play Client
homepage: https://github.com/DirectMyFile/upnp.dart
dependencies:
  http: ">=0.11.1 <0.12.0"
  quiver: ">=0.20.0 <0.29.0"
  xml: ">=2.2.1 <3.0.0"
  stack_trace: "^1.6.5"
  crypto: "^2.0.1"
