name: upnp
version: 1.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: Universal Plugin and Play Client
homepage: https://github.com/DirectMyFile/upnp.dart
dependencies:
  xml: "^3.2.0"
  crypto: "^2.0.6"
environment:
  sdk: ">=2.0.0 <3.0.0"

